project:
  type: website
  output-dir: docs

website:
  title: "IDSSS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: O kursu
      - sessions.qmd
  sidebar:
    - title: "Sessions"
      style: "docked"
      #contents: auto 
      background: secondary
      contents:
        - session_001.ipynb
        - session_002.ipynb
        - session_003.ipynb
        - session_004.ipynb
        - session_005.ipynb
        - session_006.ipynb
        - session_007.ipynb
        - session_008.ipynb
        - session_009.ipynb
        - session_010.ipynb
        #- index.qmd
        #- about.qmd
        #- section: "Sessions"
        #  contents:
            #- session_001.ipynb
    #reader-mode: true

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: style.css
    toc: true



