---
title: "O kursu"
format: 
  html:
    toc-title: Sadržaj
---

Pred Vama je **preliminarni plan kursa**. Moguće je da će pojedinačne sesije izgledati nešto drugačije od onoga što je ovde napisano, usled toga što ćemo možda morati da se prilagodimo tempu rada koji odgovara većini.

- Zadržavam pravo da menjam sadržaj specifičnih sesija, sa obzirom na to da još uvek razvijam kurikulum. Međutim, najveći deo sadržaja kursa bi trebalo da odgovara ovome što možete videti u nastavku teksta. 

**Materijali za čitanje i učenje** za svaki čas biće svima dostupni u elektronskom formatu. Podeliću ih sa vama pre časa, ili nakon časa. 

To se odnosi i na materijale koje ćemo koristiti za **domaće zadatke**. Domaći zadaci su dosta važni, zato što nećemo sve važne stvari uspeti da pokrijemo tokom lekcija (a ni ne moramo -  samostalno učenje je svakako jedna od najvažnijih veština koja nam je potrebna u bilo kojoj istraživačkoj oblasti, ne najmanje u nauci o podacima). 

U periodu između svake dve sesije, moći ćemo da ostanemo u kontaktu preko **Slack / Discord** kanala, koji ću pripremiti. Važno je da svi polaznici budu **otvoreni za razmenu ideja, pitanja i odgovora** na ovom kanalu. Zašto je to važno? **Da bismo mogli da učimo jedni od drugih.** U ranim stupnjevima programiranja često će se javljati slična pitanja i problemi, i ukoliko budemo učili jedni od drugih, uspećemo da ih lakše i brže savladamo.

## Struktura kursa

Kurs se sastoji iz dve celine: 

1. **Uvod u Python** (sesije 1 - 5)  i
2. **Uvod u mašinsko učenje** (sesije 6 - 10)

Evo i spiska pojedinačnih sesija:

- [**Sesija 1:** Intro to Python](session_001.ipynb)
- [**Sesija 2:** More Data Types & Control Flow](session_002.ipynb)
- [**Sesija 3:** Intro to Functions & Pandas](session_003.ipynb)
- [**Sesija 4:** Intro to Data Visualization](session_004.ipynb)
- [**Sesija 5:** Not in Kansas Anymore](session_005.ipynb)
- [**Sesija 6:** Intro to ML & Linear Regression](session_006.ipynb)
- [**Sesija 7:** Logistic Regression](session_007.ipynb)
- [**Sesija 8:** Love Thy Neighbor, Robot](session_008.ipynb)
- [**Sesija 9:** Can't See The Forest For The Trees](session_009.ipynb)
- [**Sesija 10:** Unsupervised Learning - Clustering](session_010.ipynb)

## Detaljniji pregled sesija

### [Sesija 1: Intro to Python](session_001.ipynb)

- Značaj i kratka istorija programskog jezika “Python”
- Okruženja u kojima je moguće raditi u Python-u 
    - Za prvi čas ćemo koristiti Google Colab - nikakva instalacija nije neophodna
- Aritmetičke operacije u Python-u
- Definisanje i upotreba varijabli
- Osnovni tipovi podataka (int, float, str)
- Operatori poređenja
- Logički operatori
- Uvod u liste 

- **Domaći zadatak:** 
    - Instalacija Pythona na lični računar, prateći priložena uputstva
    - Pronađite neku zanimljivost o Python-u, podelite je sa ostalima

---

### [Sesija 2: More Data Types & Control Flow](session_002.ipynb)
- NumPy vektori (arrays)
- Rečnici (dictionary)
- Uvod u Pandas (i DataFrame tip podataka)
- Kontrola toka u Python-u:
    - if, else i `elif` operatori
- Petlje (loops): `for` i `while` 

- **Domaći zadatak:** 
    - Upoznavanje sa tipom podataka tuple
    - Bliže upoznavanje sa svojstvima numpy vektora (arrays)
    - Rešavanje nekolicine jednostavnih programerskih zadataka uz pomoć naučenih operatora i petlji

---

### [Sesija 3: Intro to Functions & Pandas](session_003.ipynb)
- Definsanje funkcija - osnovna sintaksa + definisanje argumenata
- Produbljivanje znanja rada u paketu Pandas
- Resursi za učenje i vežbu - izvori podataka
- Kaggle, inside airbnb, eurostat, …

- **Očekivani rezultat:** Elementarno igranje sa .csv podacima pomoću paketa Pandas

---

### [Sesija 4: Intro to Data Visualization](session_004.ipynb) 
- Kratko podsećanje na tipove vizualizacije podataka: 
    - scatterplots, histograms, bar charts, box plots, heatmaps…
- Vizuelizacije koje su ugrađene u Pandas
- Vizuelizacije u paketu Matplotlib - osnovni paket za vizualizaciju u Python Data Science zajednici
- Koje još opcije za vizuelizaciju postoje?
    - Seaborn
    - Plotly
- **Ekskurs:** Može li se Python koristiti za stvaranje umetnosti? 

- **Domaći zadatak:**
    - Nekoliko vizuelizacija podataka po izboru studenata + 
    - kreativnost

---

### [Sesija 5: Not in Kansas Anymore](session_005.ipynb)

- File handling
- Handling exceptions
- Rad sa datumima
- Rad sa nedostajućim podacima (“missing data”)
- List comprehensions

---

### [Sesija 6: Intro to ML & Linear Regression](session_006.ipynb)

- Ukratko o mašinskom učenju, njegovim granama i primenama
- Supervised VS Unsupervised ML (+ semi-supervised & reinforcement learning)
- Tipični “workflow” u ML projektu u biblioteci `scikit-learn`
- Linearna regresija - kako, zašto, kada?

- **Domaći zadatak:** Primena linearne regresije na jedno istraživačko pitanje

---

### [Sesija 7: Logistic Regression](session_007.ipynb)

- Uvod u mere performanse
- Logistička regresija

### [Sesija 8: Love Thy Neighbor, Robot](session_008.ipynb)

- KNN
- SVMs 

- **Additional readings:** Naive Bayes

---

### [Sesija 9: Can't See The Forest For The Trees](session_009.ipynb)

- Decision Trees
- Random Forests 

---

### [Sesija 10: Unsupervised Learning - Clustering](session_010.ipynb)

- Intro to unsupervised learning
- K-means clustering 
- Recap of the second part of the course!

---

## Potencijalne teme - u zavisnosti od dostupnog vremena i interesovanja

- Natural Language Processing
- Dimensionality reduction
- Uvod u korišćenje paketa Streamlit, za pravljenje jednostavnih veb aplikacija
- Uvod u *web-scraping*

