---
title: "Introduction to Data Science for Social Scientists"

format: 
  html:
    toc-title: Sadržaj
---

Zdravo svima, i dobrodošli!

Hteo bih da Vas informišem o projektu koji želim da pokrenem: **"Introduction to Data Science for Social Scientists"**. 

Reč je o **besplatnom** kursu upotrebe programskog jezika **Python** i tehnika **mašinskog učenja**.

## Zašto Python?

Python je [jedan od najpopularnijih programskih jezika na svetu](https://statisticstimes.com/tech/top-computer-languages.php) i poznavanje njegovih osnova je velika omparativna prednost u svakoj profesiji. Lak je za učenje. "Otključava" vrata programiranja, i [primenljiv je u širokom nizu oblasti](https://www.javatpoint.com/python-applications).

## Zašto mašinsko učenje?

Mašinsko učenje je jedna od najvažnijih oblasti u okviru nauke o podacima. Predstavlja ekstenziju tehnika statističkog zaključivanja, sa kojima ste možda već upoznati, i koristi se za ekstrahovanje korisnih uvida u čitavom nizu oblasti. "Data Science" predstavlja simbiozu naučnog istraživanja i primene najsavremenijih analitičkih metoda na velike količine podataka kako bi se došlo do korisnih saznanja u širokom nizu oblasti. Studenti društvenih nauka poseduju dobre predispozicije da budu uspešni u ovoj oblasti, a saznanja iz nje im mogu pomoći i da budu bolji društveni naučnici.

## Šta je cilj programa?

Prvi cilj programa je da polaznici steknu dovoljno znanja iz **Python**-a da mogu samostalno da nastave učenje. Drugi cilj je da polaznici steknu dovoljno znanja iz oblasti **mašinskog učenja** da mogu da različite tehnike iz ove oblasti primene u rešavanju svojih istraživačkih pitanja. 

Voleo bih da u toku kursa što više sarađujemo, razvijamo zajedničke projekte, učimo jedni od drugih i sklapamo istraživačka partnerstva. Naglasak je na primeni naučenog. 

Cilj programa *nije* upoznavanje sa tzv. "neuronskim mrežama". 

## Šta su planirani rezultati ovog programa?

Voleo bih da svakom zainteresovanom polazniku ovaj program pruži dovoljno znanja, inspiracije i podrške da do njegovog kraja napravi **3-4 manjih data-projekata** koje može da prikaže u svom portfoliju, kao i **jedan finalni, veći, grupni projekat**. Ovo će naravno, u velikoj meri zavisiti od lične spremnosti na zalaganje svakog polaznika. Takođe, voleo bih da tokom trajanja projekta formiramo online **"biblioteku" znanja** - rešenih nedoumica, tipičnih dilema, zanimljivosti i korisnih resursa za učenje, kao i da predavanja postavimo na **Youtube**, kako bi bila dostupna svima koji se interesuju za Python i Data Science.

## Kome je program namenjen? Koji su preduslovi za učešće u njemu?

Program je namenjen s**tudentima sociologije i psihologije** sa savladanim **osnovama statistike** (više godine studija). 

- **_Zainteresovan/a sam za program, ali se ne uklapam u gore navedeni profil. Šta da radim?_**
- Pišite mi, na adresu <viskovic.vukasin@gmail.com>. Ukoliko se Vaša interesovanja, iskustvo i motivacija poklapaju sa načinom na koji je kurs zamišljen, to ne bi trebalo da bude prepreka.

Dalji preduslovi podrazumevaju radoznalost, motivisanost za samostalno istraživanje i deljenje znanja, spremnost na saradnju, posvećenost programu (spremnost da mu posvetite barem 2 sata nedeljno), poznavanje osnova statistike i rada na računaru (ukoliko, recimo, već koristite Excel ili SPSS, pohađanje kursa će Vam biti znatno olakšano) i razumevanje pročitanog na engleskom jeziku. Naravno, dobro bi bilo imati i stabilnu internet konekciju.

## Iz kojih oblasti i aktivnosti se kurs sastoji? 

Na [ovom linku](about.qmd) možete naći preliminarni plan sesija sa spiskom oblasti koje ćemo pokriti i aktivnosti kojima ćemo se baviti.

## Materijali za učenje?

Biće obezbeđeni u elektronskom formatu pre/posle svake sesije. Koristićemo delove knjiga, članke, video snimke i delove Python koda.

## Trajanje programa? Početak programa? Gde i kada se sastajemo?

Program bi trajao 3-4 meseca, sa početkom u martu. Imalo bismo ukupno oko 10 jednočasovnih do jednoipočasovnih sesija. Sastajali bismo se jednom nedeljno, verovatno subotom, preko Zoom-a ili slične
platforme. Dakle, online. Više informacija šaljem blagovremeno.

## Da li se učešće u programu plaća?

Ne, celokupan program je besplatan.

## Ko sam ja?

Zovem se Vukašin Višković. Završio sam osnovne studije sociologije na Filozofskom fakultetu u Beogradu, i master studije sociologije na Freie Univerzitetu u Berlinu. U svom akademskom i profesionalnom radu
sam koristio Python i R za analizu podataka, i u tom pogledu imam višegodišnje iskustvo. Zaposlen sam kao Data Analyst / Data Scientist na Institutu za primenjena zdravstvena istraživanja u Berlinu. Na [ovom linku](https://www.linkedin.com/in/vukasin-viskovic/) možete saznati malo više o meni (moj LinkedIn profil). 

Želim da svoje znanje podelim sa Vama, ali i da učim zajedno sa Vama i od Vas.

## Sledeći koraci? 

Slobodno upišite svoje ime i imejl adresu u polja u dnu [ovog dokumenta](https://docs.google.com/forms/d/e/1FAIpQLSfmF888QyhV5j6vbntpN_31HhV47lfazoGPqun9BJqhAigsxQ/viewform), ukoliko ste zainteresovani za program. Ovo ne znači da ste u obavezi da pohađate program, već mi samo omogućava da procenim generalnu zainteresovanost, i osmislim dalje korake. Nakon toga ću Vas kontaktirati preko imejla sa detaljnijim informacijama.

## Pitanja?

Možete mi pisati na imejl adresu: <viskovic.vukasin@gmail.com>

Tu sam da odgovorim na sva Vaša pitanja.

---

Hvala na interesovanju!

Vukašin
